### ISSUE TITLE
You broke all dependencies

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/go-wire#1]
If I wish to import `tendermint/iavl` in a repo, I use glide.
It also uses a tagged version of go-wire (eg. v0.7.2).

Yesterday all tags were removed from this repo and any attempt to use the locked version of iavl now break due to this dependency mismatch. Would it be possible to re-add the tags (at least the semver ones: v0.6.2, v0.7.{0,1,2})? At least until all the other tendermint code has properly updated.

**Comment by ethanfrey** [comment]
@jaekwon 
@ebuchman

**Comment by ebuchman** [comment]
They're on go-amino now. You should be able to just point your glide source at `tendermint/go-amino` and make this work again

**Comment by ethanfrey** [comment]
Except the branch of iavl i was using imports go-wire...
I forced this to work using `glide mirror`, but it's not nice for others.
Especially since there are (recent) tagged releases of many tendermint libraries that depend on tagged releases of go-wire.

Just nice to give a time window for "deprecation".

**Comment by ebuchman** [comment]
for sure - you can still use go-wire and just change the `source` field in the glide to point elsewhere. It should be a one line change to the glide.yaml and everything should just work (eg. its how you would point a dep to a fork)

**Comment by kentquirk** [comment]
Please don't do stuff like this. I had an engineer pulling his hair out all morning trying to figure out what was going on. I appreciate that you are trying to get Cosmos out, but some of us are trying to use Tendermint and its libraries directly. Deleting tags was not necessary and not helpful.

**Comment by ebuchman** [comment]
Very sorry about this. All tags have been pushed back to the `go-wire` repo. Will not happen again.
